apiVersion: v1
kind: Pod
metadata:
  name: mongo-persistence
  labels:
    app: mongo
spec:
  volumes:
    - name: dbvol
      hostPath:
        path: /data/mongodata
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: dbvol