apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/vagrant/k8svolumes/mypv"