apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadata-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: metadata-app
  template:
    metadata:
      name: metadata-svc
      labels:
        app: metadata-app
    spec:
      containers:
        - name: metadata-app
          image: sunitparekh/metadata:v2.0
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 3
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb://mongo/metadata