apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: NodePort
  selector:
    app: metadata-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30030
